spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: juna1234
  jpa:
    database: mysql
    # InnoDB
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secretKey: ${secretKey}
  expiration: 86400 # 24 hours
