spring:
  redis:
    host: localhost
    port: 6379
    password: ${redisPassword}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${dbPassword}

  jpa:
    database: mysql
    # InnoDB
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secretKey: ${secretKey}
  expiration: 86400 # 24 hours

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

